# This file was automatically generated by:
# mmcrust compiler 0.1.1
# 

.data	 # variable declarations follow this line
_newline:   .asciiz "\n"

.text	 # instructions follow this line
print_int:          
     li $v0, 1                               
     syscall                                 
     jal $ra                                 
print_str:          
     li $v0, 4                               
     syscall                                 
     jal $ra                                 
     .text                                   
     .globl main
                            
main:	              
.ent main           
     move $v0 0          # move return value to v-reg
                    
     li $v0, 10          # perform exit syscall from spim
     syscall                                 
.end main
          
